import re
from datetime import date
from pathlib import Path

WIDTH = 32
DIVIDER = "=" * WIDTH
TRACK_STR_MAX = 39  # fits in TRACKS[N][2][40]


def _cap(s: str, n: int = TRACK_STR_MAX) -> str:
    if len(s) > n:
        return s[: n - 3] + "..."
    return s


def _escape_cpp(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _wrap(text: str, width: int) -> list[str]:
    """Word-wrap text to width, never splitting a word across lines."""
    words = text.split()
    if not words:
        return []
    lines = []
    current = ""
    for word in words:
        if not current:
            current = word
        elif len(current) + 1 + len(word) <= width:
            current += " " + word
        else:
            lines.append(current)
            current = word
    lines.append(current)
    return lines


def preview_receipt(album_data: dict, thoughts: dict) -> None:
    """Print a formatted receipt preview to the terminal (32 chars wide)."""
    artist = album_data["artist"]
    genres = album_data.get("genres", [])
    listeners = album_data.get("popularity")
    album = album_data["album"]
    year = album_data["year"]
    tracks = album_data["tracks"]
    total = album_data["total_duration"]
    rating = thoughts.get("rating", "")
    fav = thoughts.get("fav_track", [])
    if isinstance(fav, str):
        fav = [fav] if fav else []
    notes = thoughts.get("notes", "")
    paragraph = thoughts.get("paragraph", "")

    # Header
    print(DIVIDER)
    for line in _wrap(album, WIDTH):
        print(line.center(WIDTH))
    for line in _wrap(f"{artist} ({year})", WIDTH):
        print(line.center(WIDTH))
    if genres:
        for line in _wrap(" / ".join(genres), WIDTH):
            print(line.center(WIDTH))
    if listeners is not None:
        print(f"{listeners:,} plays".center(WIDTH))
    print(DIVIDER)

    # Tracks
    for t in tracks:
        num = f"{t['number']:2d}."
        dur = t["duration"]
        marker = "*" if t["title"] in fav else " "
        prefix = f" {num} {marker}"          # e.g. "  1. *" — always 6 chars
        indent = " " * len(prefix)           # 6-space indent for continuation
        title_max = WIDTH - len(prefix) - 1 - len(dur)  # space + dur at end
        segs = _wrap(t["title"], title_max)
        for i, seg in enumerate(segs):
            pfx = prefix if i == 0 else indent
            if i == len(segs) - 1:
                pad = WIDTH - len(pfx) - len(seg) - len(dur)
                print(f"{pfx}{seg}{' ' * pad}{dur}")
            else:
                print(f"{pfx}{seg}")

    # Totals
    print(DIVIDER)
    pad = WIDTH - len("Total") - len(total) - 2
    print(f" Total{' ' * pad}{total}")
    print(DIVIDER)

    # Meta rows
    def meta_row(label: str, value: str) -> None:
        col = 12
        pfx = f" {label:<{col - 1}}"
        ind = " " * len(pfx)
        for i, seg in enumerate(_wrap(value, WIDTH - len(pfx))):
            print(f"{pfx if i == 0 else ind}{seg}")

    today = date.today()
    meta_row("Date:", f"{today.month}.{today.day}.{today.year}")
    meta_row("Rating:", rating)
    meta_row("Fav:", fav[0] if fav else "")

    # Text blocks (right-justified)
    def print_block(text: str, right: bool = False) -> None:
        if not text:
            return
        print()
        for seg in _wrap(text, WIDTH):
            print(seg.rjust(WIDTH) if right else seg)

    print_block(notes, right=False)
    print_block(paragraph)

    print(DIVIDER)


def generate_header_file(
    album_data: dict, thoughts: dict, output_path: Path
) -> None:
    """Write receipt_data.h, fully overwriting any existing file."""
    artist = _cap(_escape_cpp(album_data["artist"]))
    album = _cap(_escape_cpp(album_data["album"]))
    year = _escape_cpp(album_data["year"])
    tracks = album_data["tracks"]
    total = _escape_cpp(album_data["total_duration"])
    rating = _cap(_escape_cpp(thoughts.get("rating", "")))
    fav_raw = thoughts.get("fav_track", [])
    if isinstance(fav_raw, str):
        fav_raw = [fav_raw] if fav_raw else []
    fav = _cap(_escape_cpp(fav_raw[0] if fav_raw else ""))
    popularity = album_data.get("popularity") or 0
    tags = _cap(_escape_cpp(" / ".join(album_data.get("genres", []))))
    notes = _escape_cpp(thoughts.get("notes", ""))

    n = len(tracks)
    track_lines = []
    escaped_titles = []
    escaped_durs = []
    for t in tracks:
        title = _escape_cpp(t["title"])
        dur = _escape_cpp(t["duration"])
        escaped_titles.append(title)
        escaped_durs.append(dur)
        track_lines.append(f'  {{"{title}", "{dur}"}}')

    col_width = max(
        max((len(s) for s in escaped_titles), default=0),
        max((len(s) for s in escaped_durs), default=0),
    ) + 1  # +1 for null terminator

    tracks_body = ",\n".join(track_lines)

    header = f"""\
// AUTO-GENERATED by receipt_builder.py — do not edit
const char* ARTIST      = "{artist}";
const char* ALBUM       = "{album}";
const char* YEAR        = "{year}";
const int   TRACK_COUNT = {n};
const char  TRACKS[{n}][2][{col_width}] = {{
{tracks_body}
}};
const char* TOTAL_TIME  = "{total}";
const char* RATING      = "{rating}";
const char* FAV_TRACK   = "{fav}";
const char* NOTES       = "{notes}";
const unsigned long POPULARITY = {popularity};
const char* TAGS        = "{tags}";
"""

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header, encoding="utf-8")


def archive_receipt(
    album_data: dict, thoughts: dict, receipts_dir: Path
) -> Path:
    """Save a human-readable .md receipt to receipts/."""
    artist = album_data["artist"]
    album = album_data["album"]
    year = album_data["year"]
    tracks = album_data["tracks"]
    total = album_data["total_duration"]
    rating = thoughts.get("rating", "")
    fav_raw = thoughts.get("fav_track", [])
    if isinstance(fav_raw, str):
        fav_raw = [fav_raw] if fav_raw else []
    fav = fav_raw[0] if fav_raw else ""
    notes = thoughts.get("notes", "")
    today = date.today().isoformat()

    lines = [
        f"# {album} — {artist} ({year})",
        f"Date: {today}",
        "",
        "## Tracks",
        "",
    ]
    for t in tracks:
        lines.append(f"{t['number']:2d}. {t['title']} — {t['duration']}")
    lines += [
        "",
        f"**Total:** {total}",
        "",
        "## Review",
        "",
        f"**Rating:** {rating}",
        f"**Favorite Track:** {fav}",
        f"**Notes:** {notes}",
    ]

    receipts_dir = Path(receipts_dir)
    receipts_dir.mkdir(parents=True, exist_ok=True)

    slug = re.sub(r"[^\w\s-]", "", album.lower())
    slug = re.sub(r"[\s_]+", "-", slug).strip("-")
    filename = f"{slug}_{today}.md"
    filepath = receipts_dir / filename
    filepath.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return filepath


